### ISSUE TITLE
Build Error on M1 Macbook Pro - "No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type."

### ISSUE THREAD

**Issue by orby-will** [salrashid123/go-grpc-bazel-docker#2]
Hi there,

I am seeing the following errors when I try to build the repo.

```
ERROR: /private/var/tmp/_bazel_ldxstc/dfad75004cbe84ab14cda65c23b8d1f2/external/io_bazel_rules_go/BUILD.bazel:88:17: While resolving toolchains for target @io_bazel_rules_go//:cgo_context_data: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.
ERROR: Analysis of target '//greeter_server:greeter_server_image' failed; build aborted:

```

How to repro:

```
git clone https://github.com/salrashid123/go-grpc-bazel-docker.git
cd go-grpc-bazel-docker
bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 greeter_server:all

```
Environment
macOS Monterey Version 12.5
Chip Apple M1 Pro
Bazel: bazel 5.2.0-homebrew
Protoc: libprotoc 3.21.4

**Comment by salrashid123** [comment]
i don't have a macbook to test with (just linux).  

Can you see if adding in some specs [here](https://github.com/salrashid123/go-grpc-bazel-docker/blob/master/greeter_server/BUILD.bazel#L5)



like

```bazel
go_binary(
    name = "server",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
    goos = "linux", 
    goarch = "amd64", 
    data = [
        "//certs:CA_crt.pem",
        "//certs:grpc_server_crt.pem",   
        "//certs:grpc_server_key.pem",                
    ]      
)
```

helps?

**Comment by orby-will** [comment]
No luck either. 
However go_image with these specs worked fine.  i.e.:

go_image(
    name = "server",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
    goos = "linux", 
    goarch = "amd64", 
    data = [
        "//certs:CA_crt.pem",
        "//certs:grpc_server_crt.pem",   
        "//certs:grpc_server_key.pem",                
    ]      
)

**Comment by orby-will** [comment]
A side question. Do you need to generate and check in the echo.pb.go file? or it's mostly for being to run with go directly?

**Comment by salrashid123** [comment]
glad its working; 

you def need the `echo.pb.go` for here as that contains the protbuf definitions (since the specific app w'ere running uses grpc).

the default build here generates the pb file from scratch to make this end-to-end repro.  i do mention that you can [generate it out of band](https://github.com/salrashid123/go-grpc-bazel-docker#using-pregenerated-protopb-and-gazelle) and import it (which is faster but it defeats the intent of the sample)

**Comment by orby-will** [comment]
> 

What's workflow for generating the pb.go file and how it is used? IIUC, it not necessary if one uses bazel to build and run the application.
